services:
  - type: web
    name: tugas-tensorflow-web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    healthCheckPath: /
    autoDeploy: true
